### ISSUE TITLE
Access to the path is denied. UnixFileSystem.MoveFile

### ISSUE THREAD

**Issue by ctaggart** [ctaggart/visualfsharp-docker#4]
Using the instruction I posted, the build fails using local docker hosts such as VirtualBox or Parallels. It works fine using Travis CI and Google Cloud.

https://hub.docker.com/r/ctaggart/visualfsharp/

```
git clone https://github.com/ctaggart/visualfsharp-docker.git
cd visualfsharp-docker
docker run --rm -ti -v $PWD/template:/root/template ctaggart/visualfsharp
cd template
./build.sh
```

It fails with this error:

```
nhandled Exception: System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.UnixFileSystem.MoveFile(String sourceFullPath, String destFullPath)
   at Microsoft.DotNet.Tools.Compiler.Fsc.CompileFscCommand.Run(Stringrgs)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(Stringrgs)
   at Microsoft.DotNet.Cli.Program.Main(Stringrgs)
/usr/share/dotnet/bin/dotnet compile-fsc @/root/template/obj/Debug/dnxcore50/dotnet-compile.rsp returned Exit Code 134
```

**Comment by ctaggart** [comment]
There are a couple of fixes for this. System.IO.UnixFilesystem.MoveFile was fixed today to fall back to to copying the file and deleting the old one. Right now it tries to do a hard link and then delete the old name. Hard links do not work on docker volumes with VirtualBox and Parallels.

The File.Move is not longer necessary now that the F# compiler removed the `exe` extension requirement. A PR is already created that will fix this https://github.com/dotnet/cli/pull/1898/files#diff-a175d64eb1501e389512f1e13c8d22f1L134.

**Comment by ctaggart** [comment]
This affects `ctaggart/visualfsharp:1.0.0-alpha-160318` docker image.

**Comment by enricosada** [comment]
Atm the compile-fsc move the file .dll -> .exe in latest .NET CLI.
I'll check if fsc removed the requirement for .exe, and i'll remove the workaround (move) from compile-fsc
